#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive

export PATH=/home/admina/.rvm/gems/ruby-2.2.0/bin:/home/admina/.rvm/gems/ruby-2.2.0@global/bin:/home/admina/.rvm/rubies/ruby-2.2.0/bin:/home/admina/.rvm/bin:$PATH
export GEM_PATH=/home/admina/.rvm/gems/ruby-2.2.0:/home/admina/.rvm/gems/ruby-2.2.0@global

run deploy/before_restart
run deploy/restart && run deploy/after_restart
